namespace CareWebServiceEndpoint.Models.Upload
{
    public class BE00000005Model
    {
        public string? ADDCOVERAGEDISCOUNT1 { get; set; }
        public string? ADDCOVERAGEDISCOUNT2 { get; set; }
        public string? ADDCOVERAGEDISCOUNT3 { get; set; }
        public string? POLICYNO { get; set; }
        public string? CERTIFICATENO { get; set; }
        public string? REFNO { get; set; }
        public string? INSURED { get; set; }
        public string? ENDORSEALLF { get; set; }
        public string? EXTERNALF { get; set; }
        public string? APP_SOURCE { get; set; }
        public string? NOREFUNDF { get; set; }
        public string? EFFECTIVE_DATE { get; set; }
        public string? REASON { get; set; }
        public string? REMARKS { get; set; }
        public string? MEMO { get; set; }
        public string? FEE_AMOUNT { get; set; }
        public string? FEE_CURRENCY { get; set; }
        public string? FEE_REMARK { get; set; }
        public string? DUTY_AMOUNT { get; set; }
        public string? DUTY_CURRENCY { get; set; }
        public string? DUTY_REMARK { get; set; }
        public string? OBJ_INFO_01 { get; set; }
        public string? OBJ_INFO_02 { get; set; }
        public string? OBJ_INFO_03 { get; set; }
        public string? OBJ_INFO_04 { get; set; }
        public string? OBJ_INFO_05 { get; set; }
        public string? OBJ_INFO_06 { get; set; }
        public string? OBJ_INFO_07 { get; set; }
        public string? OBJ_INFO_08 { get; set; }
        public string? OBJ_INFO_09 { get; set; }
        public string? OBJ_INFO_10 { get; set; }
        public string? OBJ_INFO_11 { get; set; }
        public string? OBJ_INFO_12 { get; set; }
        public string? OBJ_INFO_13 { get; set; }
        public string? OBJ_INFO_14 { get; set; }
        public string? OBJ_INFO_15 { get; set; }
        public string? ADDCOVERAGE1 { get; set; }
        public string? ADDCOVERAGEREMARK1 { get; set; }
        public string? ADDRATE1 { get; set; }
        public string? ADDCOVERAGESDATE1 { get; set; }
        public string? ADDCOVERAGEEDATE1 { get; set; }
        public string? ADDCOVERAGELOADING1 { get; set; }
        public string? ADDPCALC1 { get; set; }
        public string? ADDPPRORATA1 { get; set; }
        public string? ADDUNIT1 { get; set; }
        public string? ADDINTERESTCODE1 { get; set; }
        public string? ADDINTERESTREMARK1 { get; set; }
        public string? ADDMAXLIABILITY1 { get; set; }
        public string? ADDCURRENCY1 { get; set; }
        public string? ADDSUMINSURED1 { get; set; }
        public string? ADDINTERESTCODE2 { get; set; }
        public string? ADDINTERESTREMARK2 { get; set; }
        public string? ADDMAXLIABILITY2 { get; set; }
        public string? ADDCURRENCY2 { get; set; }
        public string? ADDSUMINSURED2 { get; set; }
        public string? EMETHOD { get; set; }
        public string? BSID1 { get; set; }
        public string? BSTYPE1 { get; set; }
        public string? BSFEE1 { get; set; }
        public string? BSFeeAmount1 { get; set; }
        public string? BSID2 { get; set; }
        public string? BSTYPE2 { get; set; }
        public string? BSFEE2 { get; set; }
        public string? BSFeeAmount2 { get; set; }
        public string? BSID3 { get; set; }
        public string? BSTYPE3 { get; set; }
        public string? BSFEE3 { get; set; }
        public string? BSFeeAmount3 { get; set; }
    }
}
