using Microsoft.AspNetCore.Mvc;

namespace CareWebServiceEndpoint.Models.Upload
{
    public class UP00000001Model
    {
        public string? HOLDERID { get; set; }
        public string? INSUREDID { get; set; }
        public string? HOLDERNAME { get; set; }
        public string? INSUREDNAME { get; set; }
        public string? ADDRESS1 { get; set; }
        public string? ADDRESS2 { get; set; }
        public string? ADDRESS3 { get; set; }
        public string? CITY { get; set; }
        public string? BIRTHDATE { get; set; }
        public string? EMAIL { get; set; }
        public string? PHONE { get; set; }
        public string? MOBILE { get; set; }
        public string? ID_NO { get; set; }
        public string? TAXID { get; set; }
        public string? ZIPCODE { get; set; }
        public string? CORRESPONDENCE_ADDRESS { get; set; }
        public string? CORRESPONDENCE_EMAIL { get; set; }
        public string? CORRESPONDENCE_PHONE { get; set; }
        public string? BRANCH { get; set; }
        public string? MO { get; set; }
        public string? SEGMENT { get; set; }
        public string? STYPE { get; set; }
        public string? INSURANCE_TYPE { get; set; }
        public string? TOC { get; set; }
        public string? TOPRO { get; set; }
        public string? TOPRO_CURRENCY { get; set; }
        public string? LONG_INSURED_NAME { get; set; }
        public string? REFNO { get; set; }
        public string? STARTDATE { get; set; }
        public string? ENDDATE { get; set; }
        public string? TOPRO_TSI { get; set; }
        public string? TOPRO_ATSI { get; set; }
        public string? AUTOCALCADDITIONF { get; set; }
        public string? MASTERF { get; set; }
        public string? AUTOINFORCE { get; set; }
        public string? POLICYNO { get; set; }
        public string? REGNO { get; set; }
        public string? CONJ_POLICYNO { get; set; }
        public string? CONJ_CERTIFICATENO { get; set; }
        public string? REMARKS { get; set; }
        public string? MEMO { get; set; }
        public string? PAYORID { get; set; }
        public string? GRACEPERIOD { get; set; }
        public string? DISCOUNT { get; set; }
        public string? INSTALLMENT_DURATION { get; set; }
        public string? INSTALLMENT_FIRSTDUE { get; set; }
        public string? INSTALLMENT_FREQ { get; set; }
        public string? OBJ_INFO_01 { get; set; }
        public string? OBJ_INFO_02 { get; set; }
        public string? OBJ_INFO_03 { get; set; }
        public string? OBJ_INFO_04 { get; set; }
        public string? OBJ_INFO_05 { get; set; }
        public string? OBJ_INFO_06 { get; set; }
        public string? OBJ_INFO_07 { get; set; }
        public string? OBJ_INFO_08 { get; set; }
        public string? OBJ_INFO_09 { get; set; }
        public string? OBJ_INFO_10 { get; set; }
        public string? OBJ_INFO_11 { get; set; }
        public string? OBJ_INFO_12 { get; set; }
        public string? OBJ_INFO_13 { get; set; }
        public string? OBJ_INFO_14 { get; set; }
        public string? OBJ_INFO_15 { get; set; }
        public string? DESCRIPTION1 { get; set; }
        public string? DESCRIPTION2 { get; set; }
        public string? DESCRIPTION3 { get; set; }
        public string? DESCRIPTION4 { get; set; }
        public string? DESCRIPTION5 { get; set; }
        public string? DESCRIPTION6 { get; set; }
        public string? DESCRIPTION7 { get; set; }
        public string? DESCRIPTION8 { get; set; }
        public string? DESCRIPTION9 { get; set; }
        public string? DESCRIPTION10 { get; set; }
        public string? DESCRIPTION11 { get; set; }
        public string? DESCRIPTION12 { get; set; }
        public string? DESCRIPTION13 { get; set; }
        public string? DESCRIPTION14 { get; set; }
        public string? DESCRIPTION15 { get; set; }
        public string? COVERAGE1 { get; set; }
        public string? COVERAGE2 { get; set; }
        public string? COVERAGE3 { get; set; }
        public string? COVERAGE4 { get; set; }
        public string? COVERAGE5 { get; set; }
        public string? COVERAGE6 { get; set; }
        public string? COVERAGE7 { get; set; }
        public string? COVERAGE8 { get; set; }
        public string? COVERAGE9 { get; set; }
        public string? COVERAGE10 { get; set; }
        public string? COVERAGE11 { get; set; }
        public string? COVERAGE12 { get; set; }
        public string? COVERAGE13 { get; set; }
        public string? COVERAGE14 { get; set; }
        public string? COVERAGE15 { get; set; }
        public string? COVERAGEREMARK1 { get; set; }
        public string? COVERAGEREMARK2 { get; set; }
        public string? COVERAGEREMARK3 { get; set; }
        public string? COVERAGEREMARK4 { get; set; }
        public string? COVERAGEREMARK5 { get; set; }
        public string? COVERAGEREMARK6 { get; set; }
        public string? COVERAGEREMARK7 { get; set; }
        public string? COVERAGEREMARK8 { get; set; }
        public string? COVERAGEREMARK9 { get; set; }
        public string? COVERAGEREMARK10 { get; set; }
        public string? COVERAGEREMARK11 { get; set; }
        public string? COVERAGEREMARK12 { get; set; }
        public string? COVERAGEREMARK13 { get; set; }
        public string? COVERAGEREMARK14 { get; set; }
        public string? COVERAGEREMARK15 { get; set; }
        public string? COVERAGERATE1 { get; set; }
        public string? COVERAGERATE2 { get; set; }
        public string? COVERAGERATE3 { get; set; }
        public string? COVERAGERATE4 { get; set; }
        public string? COVERAGERATE5 { get; set; }
        public string? COVERAGERATE6 { get; set; }
        public string? COVERAGERATE7 { get; set; }
        public string? COVERAGERATE8 { get; set; }
        public string? COVERAGERATE9 { get; set; }
        public string? COVERAGERATE10 { get; set; }
        public string? COVERAGERATE11 { get; set; }
        public string? COVERAGERATE12 { get; set; }
        public string? COVERAGERATE13 { get; set; }
        public string? COVERAGERATE14 { get; set; }
        public string? COVERAGERATE15 { get; set; }
        public string? COVERAGEUNIT1 { get; set; }
        public string? COVERAGEUNIT2 { get; set; }
        public string? COVERAGEUNIT3 { get; set; }
        public string? COVERAGEUNIT4 { get; set; }
        public string? COVERAGEUNIT5 { get; set; }
        public string? COVERAGEUNIT6 { get; set; }
        public string? COVERAGEUNIT7 { get; set; }
        public string? COVERAGEUNIT8 { get; set; }
        public string? COVERAGEUNIT9 { get; set; }
        public string? COVERAGEUNIT10 { get; set; }
        public string? COVERAGEUNIT11 { get; set; }
        public string? COVERAGEUNIT12 { get; set; }
        public string? COVERAGEUNIT13 { get; set; }
        public string? COVERAGEUNIT14 { get; set; }
        public string? COVERAGEUNIT15 { get; set; }
        public string? COVERAGESDATE1 { get; set; }
        public string? COVERAGESDATE2 { get; set; }
        public string? COVERAGESDATE3 { get; set; }
        public string? COVERAGESDATE4 { get; set; }
        public string? COVERAGESDATE5 { get; set; }
        public string? COVERAGESDATE6 { get; set; }
        public string? COVERAGESDATE7 { get; set; }
        public string? COVERAGESDATE8 { get; set; }
        public string? COVERAGESDATE9 { get; set; }
        public string? COVERAGESDATE10 { get; set; }
        public string? COVERAGESDATE11 { get; set; }
        public string? COVERAGESDATE12 { get; set; }
        public string? COVERAGESDATE13 { get; set; }
        public string? COVERAGESDATE14 { get; set; }
        public string? COVERAGESDATE15 { get; set; }
        public string? COVERAGEEDATE1 { get; set; }
        public string? COVERAGEEDATE2 { get; set; }
        public string? COVERAGEEDATE3 { get; set; }
        public string? COVERAGEEDATE4 { get; set; }
        public string? COVERAGEEDATE5 { get; set; }
        public string? COVERAGEEDATE6 { get; set; }
        public string? COVERAGEEDATE7 { get; set; }
        public string? COVERAGEEDATE8 { get; set; }
        public string? COVERAGEEDATE9 { get; set; }
        public string? COVERAGEEDATE10 { get; set; }
        public string? COVERAGEEDATE11 { get; set; }
        public string? COVERAGEEDATE12 { get; set; }
        public string? COVERAGEEDATE13 { get; set; }
        public string? COVERAGEEDATE14 { get; set; }
        public string? COVERAGEEDATE15 { get; set; }
        public string? COVERAGEDISCOUNT1 { get; set; }
        public string? COVERAGEDISCOUNT2 { get; set; }
        public string? COVERAGEDISCOUNT3 { get; set; }
        public string? COVERAGEDISCOUNT4 { get; set; }
        public string? COVERAGEDISCOUNT5 { get; set; }
        public string? COVERAGEDISCOUNT6 { get; set; }
        public string? COVERAGEDISCOUNT7 { get; set; }
        public string? COVERAGEDISCOUNT8 { get; set; }
        public string? COVERAGEDISCOUNT9 { get; set; }
        public string? COVERAGEDISCOUNT10 { get; set; }
        public string? COVERAGEDISCOUNT11 { get; set; }
        public string? COVERAGEDISCOUNT12 { get; set; }
        public string? COVERAGEDISCOUNT13 { get; set; }
        public string? COVERAGEDISCOUNT14 { get; set; }
        public string? COVERAGEDISCOUNT15 { get; set; }
        public string? COVERAGEPCALC1 { get; set; }
        public string? COVERAGEPCALC2 { get; set; }
        public string? COVERAGEPCALC3 { get; set; }
        public string? COVERAGEPCALC4 { get; set; }
        public string? COVERAGEPCALC5 { get; set; }
        public string? COVERAGEPCALC6 { get; set; }
        public string? COVERAGEPCALC7 { get; set; }
        public string? COVERAGEPCALC8 { get; set; }
        public string? COVERAGEPCALC9 { get; set; }
        public string? COVERAGEPCALC10 { get; set; }
        public string? COVERAGEPCALC11 { get; set; }
        public string? COVERAGEPCALC12 { get; set; }
        public string? COVERAGEPCALC13 { get; set; }
        public string? COVERAGEPCALC14 { get; set; }
        public string? COVERAGEPCALC15 { get; set; }
        public string? COVERAGEPRORATA1 { get; set; }
        public string? COVERAGEPRORATA2 { get; set; }
        public string? COVERAGEPRORATA3 { get; set; }
        public string? COVERAGEPRORATA4 { get; set; }
        public string? COVERAGEPRORATA5 { get; set; }
        public string? COVERAGEPRORATA6 { get; set; }
        public string? COVERAGEPRORATA7 { get; set; }
        public string? COVERAGEPRORATA8 { get; set; }
        public string? COVERAGEPRORATA9 { get; set; }
        public string? COVERAGEPRORATA10 { get; set; }
        public string? COVERAGEPRORATA11 { get; set; }
        public string? COVERAGEPRORATA12 { get; set; }
        public string? COVERAGEPRORATA13 { get; set; }
        public string? COVERAGEPRORATA14 { get; set; }
        public string? COVERAGEPRORATA15 { get; set; }
        public string? COVERAGEINDEMNITY1 { get; set; }
        public string? COVERAGEINDEMNITY2 { get; set; }
        public string? COVERAGEINDEMNITY3 { get; set; }
        public string? COVERAGEINDEMNITY4 { get; set; }
        public string? COVERAGEINDEMNITY5 { get; set; }
        public string? COVERAGEINDEMNITY6 { get; set; }
        public string? COVERAGEINDEMNITY7 { get; set; }
        public string? COVERAGEINDEMNITY8 { get; set; }
        public string? COVERAGEINDEMNITY9 { get; set; }
        public string? COVERAGEINDEMNITY10 { get; set; }
        public string? COVERAGEINDEMNITY11 { get; set; }
        public string? COVERAGEINDEMNITY12 { get; set; }
        public string? COVERAGEINDEMNITY13 { get; set; }
        public string? COVERAGEINDEMNITY14 { get; set; }
        public string? COVERAGEINDEMNITY15 { get; set; }
        public string? COVERAGELOADING1 { get; set; }
        public string? COVERAGELOADING2 { get; set; }
        public string? COVERAGELOADING3 { get; set; }
        public string? COVERAGELOADING4 { get; set; }
        public string? COVERAGELOADING5 { get; set; }
        public string? COVERAGELOADING6 { get; set; }
        public string? COVERAGELOADING7 { get; set; }
        public string? COVERAGELOADING8 { get; set; }
        public string? COVERAGELOADING9 { get; set; }
        public string? COVERAGELOADING10 { get; set; }
        public string? COVERAGELOADING11 { get; set; }
        public string? COVERAGELOADING12 { get; set; }
        public string? COVERAGELOADING13 { get; set; }
        public string? COVERAGELOADING14 { get; set; }
        public string? COVERAGELOADING15 { get; set; }
        public string? INTERESTCODE1 { get; set; }
        public string? INTERESTCODE2 { get; set; }
        public string? INTERESTCODE3 { get; set; }
        public string? INTERESTCODE4 { get; set; }
        public string? INTERESTCODE5 { get; set; }
        public string? INTERESTCODE6 { get; set; }
        public string? INTERESTCODE7 { get; set; }
        public string? INTERESTCODE8 { get; set; }
        public string? INTERESTCODE9 { get; set; }
        public string? INTERESTCODE10 { get; set; }
        public string? INTERESTREMARK1 { get; set; }
        public string? INTERESTREMARK2 { get; set; }
        public string? INTERESTREMARK3 { get; set; }
        public string? INTERESTREMARK4 { get; set; }
        public string? INTERESTREMARK5 { get; set; }
        public string? INTERESTREMARK6 { get; set; }
        public string? INTERESTREMARK7 { get; set; }
        public string? INTERESTREMARK8 { get; set; }
        public string? INTERESTREMARK9 { get; set; }
        public string? INTERESTREMARK10 { get; set; }
        public string? INTERESTCURRENCY1 { get; set; }
        public string? INTERESTCURRENCY2 { get; set; }
        public string? INTERESTCURRENCY3 { get; set; }
        public string? INTERESTCURRENCY4 { get; set; }
        public string? INTERESTCURRENCY5 { get; set; }
        public string? INTERESTCURRENCY6 { get; set; }
        public string? INTERESTCURRENCY7 { get; set; }
        public string? INTERESTCURRENCY8 { get; set; }
        public string? INTERESTCURRENCY9 { get; set; }
        public string? INTERESTCURRENCY10 { get; set; }
        public string? INTERESTSUMINSURED1 { get; set; }
        public string? INTERESTSUMINSURED2 { get; set; }
        public string? INTERESTSUMINSURED3 { get; set; }
        public string? INTERESTSUMINSURED4 { get; set; }
        public string? INTERESTSUMINSURED5 { get; set; }
        public string? INTERESTSUMINSURED6 { get; set; }
        public string? INTERESTSUMINSURED7 { get; set; }
        public string? INTERESTSUMINSURED8 { get; set; }
        public string? INTERESTSUMINSURED9 { get; set; }
        public string? INTERESTSUMINSURED10 { get; set; }
        public string? MAXLIABILITY1 { get; set; }
        public string? MAXLIABILITY2 { get; set; }
        public string? MAXLIABILITY3 { get; set; }
        public string? MAXLIABILITY4 { get; set; }
        public string? MAXLIABILITY5 { get; set; }
        public string? MAXLIABILITY6 { get; set; }
        public string? MAXLIABILITY7 { get; set; }
        public string? MAXLIABILITY8 { get; set; }
        public string? MAXLIABILITY9 { get; set; }
        public string? MAXLIABILITY10 { get; set; }
        public string? DCODE1 { get; set; }
        public string? DCODE2 { get; set; }
        public string? DCODE3 { get; set; }
        public string? DCODE4 { get; set; }
        public string? DCODE5 { get; set; }
        public string? DCODE6 { get; set; }
        public string? REMARKS1 { get; set; }
        public string? REMARKS2 { get; set; }
        public string? REMARKS3 { get; set; }
        public string? REMARKS4 { get; set; }
        public string? REMARKS5 { get; set; }
        public string? REMARKS6 { get; set; }
        public string? PCTCL1 { get; set; }
        public string? PCTCL2 { get; set; }
        public string? PCTCL3 { get; set; }
        public string? PCTCL4 { get; set; }
        public string? PCTCL5 { get; set; }
        public string? PCTCL6 { get; set; }
        public string? PCTTSI1 { get; set; }
        public string? PCTTSI2 { get; set; }
        public string? PCTTSI3 { get; set; }
        public string? PCTTSI4 { get; set; }
        public string? PCTTSI5 { get; set; }
        public string? PCTTSI6 { get; set; }
        public string? CURRENCY1 { get; set; }
        public string? CURRENCY2 { get; set; }
        public string? CURRENCY3 { get; set; }
        public string? CURRENCY4 { get; set; }
        public string? CURRENCY5 { get; set; }
        public string? CURRENCY6 { get; set; }
        public string? FIXEDMAX1 { get; set; }
        public string? FIXEDMAX2 { get; set; }
        public string? FIXEDMAX3 { get; set; }
        public string? FIXEDMAX4 { get; set; }
        public string? FIXEDMAX5 { get; set; }
        public string? FIXEDMAX6 { get; set; }
        public string? FIXEDMIN1 { get; set; }
        public string? FIXEDMIN2 { get; set; }
        public string? FIXEDMIN3 { get; set; }
        public string? FIXEDMIN4 { get; set; }
        public string? FIXEDMIN5 { get; set; }
        public string? FIXEDMIN6 { get; set; }
        public string? FEE_ID { get; set; }
        public string? FEE_REMARK { get; set; }
        public string? FEE_CURRENCY { get; set; }
        public string? FEE_AMOUNT { get; set; }
        public string? DUTY_ID { get; set; }
        public string? DUTY_REMARK { get; set; }
        public string? DUTY_CURRENCY { get; set; }
        public string? DUTY_AMOUNT { get; set; }
        public string? BSID1 { get; set; }
        public string? BSID2 { get; set; }
        public string? BSID3 { get; set; }
        public string? BSTYPE1 { get; set; }
        public string? BSTYPE2 { get; set; }
        public string? BSTYPE3 { get; set; }
        public string? BSFEE1 { get; set; }
        public string? BSFEE2 { get; set; }
        public string? BSFEE3 { get; set; }
        public string? CLAUSE1 { get; set; }
        public string? CLAUSE2 { get; set; }
        public string? CLAUSE3 { get; set; }
        public string? CLAUSE4 { get; set; }
        public string? CLAUSE5 { get; set; }
        public string? CLAUSE6 { get; set; }
        public string? CLAUSE7 { get; set; }
        public string? CLAUSE8 { get; set; }
        public string? CLAUSE9 { get; set; }
        public string? CLAUSE10 { get; set; }
        public string? CLAUSE11 { get; set; }
        public string? CLAUSE12 { get; set; }
        public string? CLAUSE13 { get; set; }
        public string? CLAUSE14 { get; set; }
        public string? CLAUSE15 { get; set; }
        public string? CLAUSE16 { get; set; }
        public string? LEADERID { get; set; }
        public string? LEADERSHARE { get; set; }
        public string? LEADERFEE { get; set; }
        public string? MEMBERID1 { get; set; }
        public string? MEMBERID2 { get; set; }
        public string? MEMBERID3 { get; set; }
        public string? MEMBERSHARE1 { get; set; }
        public string? MEMBERSHARE2 { get; set; }
        public string? MEMBERSHARE3 { get; set; }
        public string? MEMBERCOMM1 { get; set; }
        public string? MEMBERCOMM2 { get; set; }
        public string? MEMBERCOMM3 { get; set; }
        public string? MEMBERHF1 { get; set; }
        public string? MEMBERHF2 { get; set; }
        public string? MEMBERHF3 { get; set; }
        public string? MEMBERPCOLLECTIONF1 { get; set; }
        public string? MEMBERPCOLLECTIONF2 { get; set; }
        public string? MEMBERPCOLLECTIONF3 { get; set; }
        public string? MEMBERCCOLLECTIONF1 { get; set; }
        public string? MEMBERCCOLLECTIONF2 { get; set; }
        public string? MEMBERCCOLLECTIONF3 { get; set; }
        public string? EMETHOD { get; set; }
        public string? XPID { get; set; }
        public string? XPSHARE { get; set; }
        public string? CID { get; set; }
        public string? CSHARE { get; set; }
        public string? QID { get; set; }
        public string? QSHARE { get; set; }
        public string? SP1ID { get; set; }
        public string? SP1SHARE { get; set; }
        public string? SP2ID { get; set; }
        public string? SP2SHARE { get; set; }
        public string? SP3ID { get; set; }
        public string? SP3SHARE { get; set; }
        public string? SHORTFALL { get; set; }
        public string? AFID { get; set; }
        public string? AFSHARE { get; set; }
        public string? FACOUT1ID { get; set; }
        public string? FACOUT1RATE { get; set; }
        public string? FACOUT1SHARE { get; set; }
        public string? FACOUT1COMM { get; set; }
        public string? FACOUT1WPC { get; set; }
        public string? FACOUT2ID { get; set; }
        public string? FACOUT2RATE { get; set; }
        public string? FACOUT2SHARE { get; set; }
        public string? FACOUT2COMM { get; set; }
        public string? FACOUT2WPC { get; set; }
        public string? FACOUT3ID { get; set; }
        public string? FACOUT3RATE { get; set; }
        public string? FACOUT3SHARE { get; set; }
        public string? FACOUT3COMM { get; set; }
        public string? FACOUT3WPC { get; set; }
        public string? VOYAGEFROM { get; set; }
        public string? VOYAGETO { get; set; }
        public string? TRANSHIPMENT { get; set; }
        public string? ATANDFROM { get; set; }
        public string? TRANSTO { get; set; }
        public string? CONSIGNEE { get; set; }
        public string? CONSIGNEE_ADDRESS { get; set; }
    }
}
