namespace CareWebServiceEndpoint.Models.Upload
{
    public class UP00000007Model
    {
        public string? STYPE { get; set; }
        public string? MASTERF { get; set; }
        public string? BRANCH { get; set; }
        public string? HOLDER { get; set; }
        public string? MO { get; set; }
        public string? SEGMENT { get; set; }
        public string? TOC { get; set; }
        public string? REGNO { get; set; }
        public string? InsuredID { get; set; }
        public string? INSURED { get; set; }
        public string? INCEPTION { get; set; }
        public string? EXPIRY { get; set; }
        public string? REFNO { get; set; }
        public string? OBJ_INFO_01 { get; set; }
        public string? OBJ_INFO_02 { get; set; }
        public string? OBJ_INFO_03 { get; set; }
        public string? OBJ_INFO_04 { get; set; }
        public string? OBJ_INFO_05 { get; set; }
        public string? OBJ_INFO_06 { get; set; }
        public string? OBJ_INFO_07 { get; set; }
        public string? OBJ_INFO_08 { get; set; }
        public string? OBJ_INFO_09 { get; set; }
        public string? OBJ_INFO_10 { get; set; }
        public string? OBJ_INFO_11 { get; set; }
        public string? OBJ_INFO_12 { get; set; }
        public string? OBJ_INFO_13 { get; set; }
        public string? OBJ_INFO_14 { get; set; }
        public string? OBJ_INFO_15 { get; set; }
        public string? OBJ_INFO_16 { get; set; }
        public string? MAINCOVERAGE { get; set; }
        public string? MAINCOVERAGEREMARK { get; set; }
        public string? MAINRATE { get; set; }
        public string? MAINUNIT { get; set; }
        public string? MAINCOVERAGESDATE { get; set; }
        public string? MAINCOVERAGEEDATE { get; set; }
        public string? PCALC { get; set; }
        public string? ADDCOVERAGE1 { get; set; }
        public string? ADDCOVERAGEREMARK1 { get; set; }
        public string? ADDRATE1 { get; set; }
        public string? ADDUNIT1 { get; set; }
        public string? ADDPCALC1 { get; set; }
        public string? ADDCOVERAGESDATE1 { get; set; }
        public string? ADDCOVERAGEEDATE1 { get; set; }
        public string? ADDINDEMNITY1 { get; set; }
        public string? ADDCOVERAGE2 { get; set; }
        public string? ADDCOVERAGEREMARK2 { get; set; }
        public string? ADDRATE2 { get; set; }
        public string? ADDUNIT2 { get; set; }
        public string? ADDPCALC2 { get; set; }
        public string? ADDCOVERAGESDATE2 { get; set; }
        public string? ADDCOVERAGEEDATE2 { get; set; }
        public string? ADDINDEMNITY2 { get; set; }
        public string? ADDCOVERAGE3 { get; set; }
        public string? ADDCOVERAGEREMARK3 { get; set; }
        public string? ADDRATE3 { get; set; }
        public string? ADDUNIT3 { get; set; }
        public string? ADDPCALC3 { get; set; }
        public string? ADDCOVERAGESDATE3 { get; set; }
        public string? ADDCOVERAGEEDATE3 { get; set; }
        public string? ADDINDEMNITY3 { get; set; }
        public string? ADDCOVERAGE4 { get; set; }
        public string? ADDCOVERAGEREMARK4 { get; set; }
        public string? ADDRATE4 { get; set; }
        public string? ADDUNIT4 { get; set; }
        public string? ADDPCALC4 { get; set; }
        public string? ADDCOVERAGESDATE4 { get; set; }
        public string? ADDCOVERAGEEDATE4 { get; set; }
        public string? ADDINDEMNITY4 { get; set; }
        public string? ADDCOVERAGE5 { get; set; }
        public string? ADDCOVERAGEREMARK5 { get; set; }
        public string? ADDRATE5 { get; set; }
        public string? ADDUNIT5 { get; set; }
        public string? ADDPCALC5 { get; set; }
        public string? ADDCOVERAGESDATE5 { get; set; }
        public string? ADDCOVERAGEEDATE5 { get; set; }
        public string? ADDINDEMNITY5 { get; set; }
        public string? ADDCOVERAGE6 { get; set; }
        public string? ADDCOVERAGEREMARK6 { get; set; }
        public string? ADDRATE6 { get; set; }
        public string? ADDUNIT6 { get; set; }
        public string? ADDPCALC6 { get; set; }
        public string? ADDCOVERAGESDATE6 { get; set; }
        public string? ADDCOVERAGEEDATE6 { get; set; }
        public string? ADDINDEMNITY6 { get; set; }
        public string? ADDCOVERAGE7 { get; set; }
        public string? ADDCOVERAGEREMARK7 { get; set; }
        public string? ADDRATE7 { get; set; }
        public string? ADDUNIT7 { get; set; }
        public string? ADDPCALC7 { get; set; }
        public string? ADDCOVERAGESDATE7 { get; set; }
        public string? ADDCOVERAGEEDATE7 { get; set; }
        public string? ADDINDEMNITY7 { get; set; }
        public string? ADDCOVERAGE8 { get; set; }
        public string? ADDCOVERAGEREMARK8 { get; set; }
        public string? ADDRATE8 { get; set; }
        public string? ADDUNIT8 { get; set; }
        public string? ADDPCALC8 { get; set; }
        public string? ADDCOVERAGESDATE8 { get; set; }
        public string? ADDCOVERAGEEDATE8 { get; set; }
        public string? ADDINDEMNITY8 { get; set; }
        public string? ADDCOVERAGE9 { get; set; }
        public string? ADDCOVERAGEREMARK9 { get; set; }
        public string? ADDRATE9 { get; set; }
        public string? ADDUNIT9 { get; set; }
        public string? ADDPCALC9 { get; set; }
        public string? ADDCOVERAGESDATE9 { get; set; }
        public string? ADDCOVERAGEEDATE9 { get; set; }
        public string? ADDINDEMNITY9 { get; set; }
        public string? ADDCOVERAGE10 { get; set; }
        public string? ADDCOVERAGEREMARK10 { get; set; }
        public string? ADDRATE10 { get; set; }
        public string? ADDUNIT10 { get; set; }
        public string? ADDPCALC10 { get; set; }
        public string? ADDCOVERAGESDATE10 { get; set; }
        public string? ADDCOVERAGEEDATE10 { get; set; }
        public string? ADDINDEMNITY10 { get; set; }
        public string? ADDCOVERAGE11 { get; set; }
        public string? ADDCOVERAGEREMARK11 { get; set; }
        public string? ADDRATE11 { get; set; }
        public string? ADDUNIT11 { get; set; }
        public string? ADDPCALC11 { get; set; }
        public string? ADDCOVERAGESDATE11 { get; set; }
        public string? ADDCOVERAGEEDATE11 { get; set; }
        public string? ADDINDEMNITY11 { get; set; }
        public string? ADDCOVERAGE12 { get; set; }
        public string? ADDCOVERAGEREMARK12 { get; set; }
        public string? ADDRATE12 { get; set; }
        public string? ADDUNIT12 { get; set; }
        public string? ADDPCALC12 { get; set; }
        public string? ADDCOVERAGESDATE12 { get; set; }
        public string? ADDCOVERAGEEDATE12 { get; set; }
        public string? ADDINDEMNITY12 { get; set; }
        public string? ADDCOVERAGE13 { get; set; }
        public string? ADDCOVERAGEREMARK13 { get; set; }
        public string? ADDRATE13 { get; set; }
        public string? ADDUNIT13 { get; set; }
        public string? ADDPCALC13 { get; set; }
        public string? ADDCOVERAGESDATE13 { get; set; }
        public string? ADDCOVERAGEEDATE13 { get; set; }
        public string? ADDINDEMNITY13 { get; set; }
        public string? ADDCOVERAGE14 { get; set; }
        public string? ADDCOVERAGEREMARK14 { get; set; }
        public string? ADDRATE14 { get; set; }
        public string? ADDUNIT14 { get; set; }
        public string? ADDPCALC14 { get; set; }
        public string? ADDCOVERAGESDATE14 { get; set; }
        public string? ADDCOVERAGEEDATE14 { get; set; }
        public string? ADDINDEMNITY14 { get; set; }
        public string? ADDCOVERAGE15 { get; set; }
        public string? ADDCOVERAGEREMARK15 { get; set; }
        public string? ADDRATE15 { get; set; }
        public string? ADDUNIT15 { get; set; }
        public string? ADDPCALC15 { get; set; }
        public string? ADDCOVERAGESDATE15 { get; set; }
        public string? ADDCOVERAGEEDATE15 { get; set; }
        public string? ADDINDEMNITY15 { get; set; }
        public string? ADDCOVERAGE16 { get; set; }
        public string? ADDCOVERAGEREMARK16 { get; set; }
        public string? ADDRATE16 { get; set; }
        public string? ADDUNIT16 { get; set; }
        public string? ADDPCALC16 { get; set; }
        public string? ADDCOVERAGESDATE16 { get; set; }
        public string? ADDCOVERAGEEDATE16 { get; set; }
        public string? ADDINDEMNITY16 { get; set; }
        public string? ADDCOVERAGE17 { get; set; }
        public string? ADDCOVERAGEREMARK17 { get; set; }
        public string? ADDRATE17 { get; set; }
        public string? ADDUNIT17 { get; set; }
        public string? ADDPCALC17 { get; set; }
        public string? ADDCOVERAGESDATE17 { get; set; }
        public string? ADDCOVERAGEEDATE17 { get; set; }
        public string? ADDINDEMNITY17 { get; set; }
        public string? ADDCOVERAGE18 { get; set; }
        public string? ADDCOVERAGEREMARK18 { get; set; }
        public string? ADDRATE18 { get; set; }
        public string? ADDUNIT18 { get; set; }
        public string? ADDPCALC18 { get; set; }
        public string? ADDCOVERAGESDATE18 { get; set; }
        public string? ADDCOVERAGEEDATE18 { get; set; }
        public string? ADDINDEMNITY18 { get; set; }
        public string? ADDCOVERAGE19 { get; set; }
        public string? ADDCOVERAGEREMARK19 { get; set; }
        public string? ADDRATE19 { get; set; }
        public string? ADDUNIT19 { get; set; }
        public string? ADDPCALC19 { get; set; }
        public string? ADDCOVERAGESDATE19 { get; set; }
        public string? ADDCOVERAGEEDATE19 { get; set; }
        public string? ADDINDEMNITY19 { get; set; }
        public string? ADDCOVERAGE20 { get; set; }
        public string? ADDCOVERAGEREMARK20 { get; set; }
        public string? ADDRATE20 { get; set; }
        public string? ADDUNIT20 { get; set; }
        public string? ADDPCALC20 { get; set; }
        public string? ADDCOVERAGESDATE20 { get; set; }
        public string? ADDCOVERAGEEDATE20 { get; set; }
        public string? ADDINDEMNITY20 { get; set; }
        public string? ADDCOVERAGE21 { get; set; }
        public string? ADDCOVERAGEREMARK21 { get; set; }
        public string? ADDRATE21 { get; set; }
        public string? ADDUNIT21 { get; set; }
        public string? ADDPCALC21 { get; set; }
        public string? ADDCOVERAGESDATE21 { get; set; }
        public string? ADDCOVERAGEEDATE21 { get; set; }
        public string? ADDINDEMNITY21 { get; set; }
        public string? ADDCOVERAGE22 { get; set; }
        public string? ADDCOVERAGEREMARK22 { get; set; }
        public string? ADDRATE22 { get; set; }
        public string? ADDUNIT22 { get; set; }
        public string? ADDPCALC22 { get; set; }
        public string? ADDCOVERAGESDATE22 { get; set; }
        public string? ADDCOVERAGEEDATE22 { get; set; }
        public string? ADDINDEMNITY22 { get; set; }
        public string? ADDCOVERAGE23 { get; set; }
        public string? ADDCOVERAGEREMARK23 { get; set; }
        public string? ADDRATE23 { get; set; }
        public string? ADDUNIT23 { get; set; }
        public string? ADDPCALC23 { get; set; }
        public string? ADDCOVERAGESDATE23 { get; set; }
        public string? ADDCOVERAGEEDATE23 { get; set; }
        public string? ADDINDEMNITY23 { get; set; }
        public string? ADDCOVERAGE24 { get; set; }
        public string? ADDCOVERAGEREMARK24 { get; set; }
        public string? ADDRATE24 { get; set; }
        public string? ADDUNIT24 { get; set; }
        public string? ADDPCALC24 { get; set; }
        public string? ADDCOVERAGESDATE24 { get; set; }
        public string? ADDCOVERAGEEDATE24 { get; set; }
        public string? ADDINDEMNITY24 { get; set; }
        public string? ADDCOVERAGE25 { get; set; }
        public string? ADDCOVERAGEREMARK25 { get; set; }
        public string? ADDRATE25 { get; set; }
        public string? ADDUNIT25 { get; set; }
        public string? ADDPCALC25 { get; set; }
        public string? ADDCOVERAGESDATE25 { get; set; }
        public string? ADDCOVERAGEEDATE25 { get; set; }
        public string? ADDINDEMNITY25 { get; set; }
        public string? ADDCOVERAGE26 { get; set; }
        public string? ADDCOVERAGEREMARK26 { get; set; }
        public string? ADDRATE26 { get; set; }
        public string? ADDUNIT26 { get; set; }
        public string? ADDPCALC26 { get; set; }
        public string? ADDCOVERAGESDATE26 { get; set; }
        public string? ADDCOVERAGEEDATE26 { get; set; }
        public string? ADDINDEMNITY26 { get; set; }
        public string? ADDCOVERAGE27 { get; set; }
        public string? ADDCOVERAGEREMARK27 { get; set; }
        public string? ADDRATE27 { get; set; }
        public string? ADDUNIT27 { get; set; }
        public string? ADDPCALC27 { get; set; }
        public string? ADDCOVERAGESDATE27 { get; set; }
        public string? ADDCOVERAGEEDATE27 { get; set; }
        public string? ADDINDEMNITY27 { get; set; }
        public string? ADDCOVERAGE28 { get; set; }
        public string? ADDCOVERAGEREMARK28 { get; set; }
        public string? ADDRATE28 { get; set; }
        public string? ADDUNIT28 { get; set; }
        public string? ADDPCALC28 { get; set; }
        public string? ADDCOVERAGESDATE28 { get; set; }
        public string? ADDCOVERAGEEDATE28 { get; set; }
        public string? ADDINDEMNITY28 { get; set; }
        public string? ADDCOVERAGE29 { get; set; }
        public string? ADDCOVERAGEREMARK29 { get; set; }
        public string? ADDRATE29 { get; set; }
        public string? ADDUNIT29 { get; set; }
        public string? ADDPCALC29 { get; set; }
        public string? ADDCOVERAGESDATE29 { get; set; }
        public string? ADDCOVERAGEEDATE29 { get; set; }
        public string? ADDINDEMNITY29 { get; set; }
        public string? ADDCOVERAGE30 { get; set; }
        public string? ADDCOVERAGEREMARK30 { get; set; }
        public string? ADDRATE30 { get; set; }
        public string? ADDUNIT30 { get; set; }
        public string? ADDPCALC30 { get; set; }
        public string? ADDCOVERAGESDATE30 { get; set; }
        public string? ADDCOVERAGEEDATE30 { get; set; }
        public string? ADDINDEMNITY30 { get; set; }
        public string? ADDCOVERAGE31 { get; set; }
        public string? ADDCOVERAGEREMARK31 { get; set; }
        public string? ADDRATE31 { get; set; }
        public string? ADDUNIT31 { get; set; }
        public string? ADDPCALC31 { get; set; }
        public string? ADDCOVERAGESDATE31 { get; set; }
        public string? ADDCOVERAGEEDATE31 { get; set; }
        public string? ADDINDEMNITY31 { get; set; }
        public string? ADDCOVERAGE32 { get; set; }
        public string? ADDCOVERAGEREMARK32 { get; set; }
        public string? ADDRATE32 { get; set; }
        public string? ADDUNIT32 { get; set; }
        public string? ADDPCALC32 { get; set; }
        public string? ADDCOVERAGESDATE32 { get; set; }
        public string? ADDCOVERAGEEDATE32 { get; set; }
        public string? ADDINDEMNITY32 { get; set; }
        public string? ADDCOVERAGE33 { get; set; }
        public string? ADDCOVERAGEREMARK33 { get; set; }
        public string? ADDRATE33 { get; set; }
        public string? ADDUNIT33 { get; set; }
        public string? ADDPCALC33 { get; set; }
        public string? ADDCOVERAGESDATE33 { get; set; }
        public string? ADDCOVERAGEEDATE33 { get; set; }
        public string? ADDINDEMNITY33 { get; set; }
        public string? ADDCOVERAGE34 { get; set; }
        public string? ADDCOVERAGEREMARK34 { get; set; }
        public string? ADDRATE34 { get; set; }
        public string? ADDUNIT34 { get; set; }
        public string? ADDPCALC34 { get; set; }
        public string? ADDCOVERAGESDATE34 { get; set; }
        public string? ADDCOVERAGEEDATE34 { get; set; }
        public string? ADDINDEMNITY34 { get; set; }
        public string? ADDCOVERAGE35 { get; set; }
        public string? ADDCOVERAGEREMARK35 { get; set; }
        public string? ADDRATE35 { get; set; }
        public string? ADDUNIT35 { get; set; }
        public string? ADDPCALC35 { get; set; }
        public string? ADDCOVERAGESDATE35 { get; set; }
        public string? ADDCOVERAGEEDATE35 { get; set; }
        public string? ADDINDEMNITY35 { get; set; }
        public string? ADDCOVERAGE36 { get; set; }
        public string? ADDCOVERAGEREMARK36 { get; set; }
        public string? ADDRATE36 { get; set; }
        public string? ADDUNIT36 { get; set; }
        public string? ADDPCALC36 { get; set; }
        public string? ADDCOVERAGESDATE36 { get; set; }
        public string? ADDCOVERAGEEDATE36 { get; set; }
        public string? ADDINDEMNITY36 { get; set; }
        public string? ADDCOVERAGE37 { get; set; }
        public string? ADDCOVERAGEREMARK37 { get; set; }
        public string? ADDRATE37 { get; set; }
        public string? ADDUNIT37 { get; set; }
        public string? ADDPCALC37 { get; set; }
        public string? ADDCOVERAGESDATE37 { get; set; }
        public string? ADDCOVERAGEEDATE37 { get; set; }
        public string? ADDINDEMNITY37 { get; set; }
        public string? ADDCOVERAGE38 { get; set; }
        public string? ADDCOVERAGEREMARK38 { get; set; }
        public string? ADDRATE38 { get; set; }
        public string? ADDUNIT38 { get; set; }
        public string? ADDPCALC38 { get; set; }
        public string? ADDCOVERAGESDATE38 { get; set; }
        public string? ADDCOVERAGEEDATE38 { get; set; }
        public string? ADDINDEMNITY38 { get; set; }
        public string? ADDCOVERAGE39 { get; set; }
        public string? ADDCOVERAGEREMARK39 { get; set; }
        public string? ADDRATE39 { get; set; }
        public string? ADDUNIT39 { get; set; }
        public string? ADDPCALC39 { get; set; }
        public string? ADDCOVERAGESDATE39 { get; set; }
        public string? ADDCOVERAGEEDATE39 { get; set; }
        public string? ADDINDEMNITY39 { get; set; }
        public string? ADDCOVERAGE40 { get; set; }
        public string? ADDCOVERAGEREMARK40 { get; set; }
        public string? ADDRATE40 { get; set; }
        public string? ADDUNIT40 { get; set; }
        public string? ADDPCALC40 { get; set; }
        public string? ADDCOVERAGESDATE40 { get; set; }
        public string? ADDCOVERAGEEDATE40 { get; set; }
        public string? ADDINDEMNITY40 { get; set; }
        public string? ADDCOVERAGE41 { get; set; }
        public string? ADDCOVERAGEREMARK41 { get; set; }
        public string? ADDRATE41 { get; set; }
        public string? ADDUNIT41 { get; set; }
        public string? ADDPCALC41 { get; set; }
        public string? ADDCOVERAGESDATE41 { get; set; }
        public string? ADDCOVERAGEEDATE41 { get; set; }
        public string? ADDINDEMNITY41 { get; set; }
        public string? ADDCOVERAGE42 { get; set; }
        public string? ADDCOVERAGEREMARK42 { get; set; }
        public string? ADDRATE42 { get; set; }
        public string? ADDUNIT42 { get; set; }
        public string? ADDPCALC42 { get; set; }
        public string? ADDCOVERAGESDATE42 { get; set; }
        public string? ADDCOVERAGEEDATE42 { get; set; }
        public string? ADDINDEMNITY42 { get; set; }
        public string? ADDCOVERAGE43 { get; set; }
        public string? ADDCOVERAGEREMARK43 { get; set; }
        public string? ADDRATE43 { get; set; }
        public string? ADDUNIT43 { get; set; }
        public string? ADDPCALC43 { get; set; }
        public string? ADDCOVERAGESDATE43 { get; set; }
        public string? ADDCOVERAGEEDATE43 { get; set; }
        public string? ADDINDEMNITY43 { get; set; }
        public string? ADDCOVERAGE44 { get; set; }
        public string? ADDCOVERAGEREMARK44 { get; set; }
        public string? ADDRATE44 { get; set; }
        public string? ADDUNIT44 { get; set; }
        public string? ADDPCALC44 { get; set; }
        public string? ADDCOVERAGESDATE44 { get; set; }
        public string? ADDCOVERAGEEDATE44 { get; set; }
        public string? ADDINDEMNITY44 { get; set; }
        public string? ADDCOVERAGE45 { get; set; }
        public string? ADDCOVERAGEREMARK45 { get; set; }
        public string? ADDRATE45 { get; set; }
        public string? ADDUNIT45 { get; set; }
        public string? ADDPCALC45 { get; set; }
        public string? ADDCOVERAGESDATE45 { get; set; }
        public string? ADDCOVERAGEEDATE45 { get; set; }
        public string? ADDINDEMNITY45 { get; set; }
        public string? ADDCOVERAGE46 { get; set; }
        public string? ADDCOVERAGEREMARK46 { get; set; }
        public string? ADDRATE46 { get; set; }
        public string? ADDUNIT46 { get; set; }
        public string? ADDPCALC46 { get; set; }
        public string? ADDCOVERAGESDATE46 { get; set; }
        public string? ADDCOVERAGEEDATE46 { get; set; }
        public string? ADDINDEMNITY46 { get; set; }
        public string? ADDCOVERAGE47 { get; set; }
        public string? ADDCOVERAGEREMARK47 { get; set; }
        public string? ADDRATE47 { get; set; }
        public string? ADDUNIT47 { get; set; }
        public string? ADDPCALC47 { get; set; }
        public string? ADDCOVERAGESDATE47 { get; set; }
        public string? ADDCOVERAGEEDATE47 { get; set; }
        public string? ADDINDEMNITY47 { get; set; }
        public string? ADDCOVERAGE48 { get; set; }
        public string? ADDCOVERAGEREMARK48 { get; set; }
        public string? ADDRATE48 { get; set; }
        public string? ADDUNIT48 { get; set; }
        public string? ADDPCALC48 { get; set; }
        public string? ADDCOVERAGESDATE48 { get; set; }
        public string? ADDCOVERAGEEDATE48 { get; set; }
        public string? ADDINDEMNITY48 { get; set; }
        public string? ADDCOVERAGE49 { get; set; }
        public string? ADDCOVERAGEREMARK49 { get; set; }
        public string? ADDRATE49 { get; set; }
        public string? ADDUNIT49 { get; set; }
        public string? ADDPCALC49 { get; set; }
        public string? ADDCOVERAGESDATE49 { get; set; }
        public string? ADDCOVERAGEEDATE49 { get; set; }
        public string? ADDINDEMNITY49 { get; set; }
        public string? ADDCOVERAGE50 { get; set; }
        public string? ADDCOVERAGEREMARK50 { get; set; }
        public string? ADDRATE50 { get; set; }
        public string? ADDUNIT50 { get; set; }
        public string? ADDPCALC50 { get; set; }
        public string? ADDCOVERAGESDATE50 { get; set; }
        public string? ADDCOVERAGEEDATE50 { get; set; }
        public string? ADDINDEMNITY50 { get; set; }
        public string? ADDCOVERAGE51 { get; set; }
        public string? ADDCOVERAGEREMARK51 { get; set; }
        public string? ADDRATE51 { get; set; }
        public string? ADDUNIT51 { get; set; }
        public string? ADDPCALC51 { get; set; }
        public string? ADDCOVERAGESDATE51 { get; set; }
        public string? ADDCOVERAGEEDATE51 { get; set; }
        public string? ADDINDEMNITY51 { get; set; }
        public string? ADDCOVERAGE52 { get; set; }
        public string? ADDCOVERAGEREMARK52 { get; set; }
        public string? ADDRATE52 { get; set; }
        public string? ADDUNIT52 { get; set; }
        public string? ADDPCALC52 { get; set; }
        public string? ADDCOVERAGESDATE52 { get; set; }
        public string? ADDCOVERAGEEDATE52 { get; set; }
        public string? ADDINDEMNITY52 { get; set; }
        public string? ADDCOVERAGE53 { get; set; }
        public string? ADDCOVERAGEREMARK53 { get; set; }
        public string? ADDRATE53 { get; set; }
        public string? ADDUNIT53 { get; set; }
        public string? ADDPCALC53 { get; set; }
        public string? ADDCOVERAGESDATE53 { get; set; }
        public string? ADDCOVERAGEEDATE53 { get; set; }
        public string? ADDINDEMNITY53 { get; set; }
        public string? ADDCOVERAGE54 { get; set; }
        public string? ADDCOVERAGEREMARK54 { get; set; }
        public string? ADDRATE54 { get; set; }
        public string? ADDUNIT54 { get; set; }
        public string? ADDPCALC54 { get; set; }
        public string? ADDCOVERAGESDATE54 { get; set; }
        public string? ADDCOVERAGEEDATE54 { get; set; }
        public string? ADDINDEMNITY54 { get; set; }
        public string? ADDCOVERAGE55 { get; set; }
        public string? ADDCOVERAGEREMARK55 { get; set; }
        public string? ADDRATE55 { get; set; }
        public string? ADDUNIT55 { get; set; }
        public string? ADDPCALC55 { get; set; }
        public string? ADDCOVERAGESDATE55 { get; set; }
        public string? ADDCOVERAGEEDATE55 { get; set; }
        public string? ADDINDEMNITY55 { get; set; }
        public string? ADDCOVERAGE56 { get; set; }
        public string? ADDCOVERAGEREMARK56 { get; set; }
        public string? ADDRATE56 { get; set; }
        public string? ADDUNIT56 { get; set; }
        public string? ADDPCALC56 { get; set; }
        public string? ADDCOVERAGESDATE56 { get; set; }
        public string? ADDCOVERAGEEDATE56 { get; set; }
        public string? ADDINDEMNITY56 { get; set; }
        public string? ADDCOVERAGE57 { get; set; }
        public string? ADDCOVERAGEREMARK57 { get; set; }
        public string? ADDRATE57 { get; set; }
        public string? ADDUNIT57 { get; set; }
        public string? ADDPCALC57 { get; set; }
        public string? ADDCOVERAGESDATE57 { get; set; }
        public string? ADDCOVERAGEEDATE57 { get; set; }
        public string? ADDINDEMNITY57 { get; set; }
        public string? ADDCOVERAGE58 { get; set; }
        public string? ADDCOVERAGEREMARK58 { get; set; }
        public string? ADDRATE58 { get; set; }
        public string? ADDUNIT58 { get; set; }
        public string? ADDPCALC58 { get; set; }
        public string? ADDCOVERAGESDATE58 { get; set; }
        public string? ADDCOVERAGEEDATE58 { get; set; }
        public string? ADDINDEMNITY58 { get; set; }
        public string? ADDCOVERAGE59 { get; set; }
        public string? ADDCOVERAGEREMARK59 { get; set; }
        public string? ADDRATE59 { get; set; }
        public string? ADDUNIT59 { get; set; }
        public string? ADDPCALC59 { get; set; }
        public string? ADDCOVERAGESDATE59 { get; set; }
        public string? ADDCOVERAGEEDATE59 { get; set; }
        public string? ADDINDEMNITY59 { get; set; }
        public string? ADDCOVERAGE60 { get; set; }
        public string? ADDCOVERAGEREMARK60 { get; set; }
        public string? ADDRATE60 { get; set; }
        public string? ADDUNIT60 { get; set; }
        public string? ADDPCALC60 { get; set; }
        public string? ADDCOVERAGESDATE60 { get; set; }
        public string? ADDCOVERAGEEDATE60 { get; set; }
        public string? ADDINDEMNITY60 { get; set; }
        public string? ADDCOVERAGE61 { get; set; }
        public string? ADDCOVERAGEREMARK61 { get; set; }
        public string? ADDRATE61 { get; set; }
        public string? ADDUNIT61 { get; set; }
        public string? ADDPCALC61 { get; set; }
        public string? ADDCOVERAGESDATE61 { get; set; }
        public string? ADDCOVERAGEEDATE61 { get; set; }
        public string? ADDINDEMNITY61 { get; set; }
        public string? ADDCOVERAGE62 { get; set; }
        public string? ADDCOVERAGEREMARK62 { get; set; }
        public string? ADDRATE62 { get; set; }
        public string? ADDUNIT62 { get; set; }
        public string? ADDPCALC62 { get; set; }
        public string? ADDCOVERAGESDATE62 { get; set; }
        public string? ADDCOVERAGEEDATE62 { get; set; }
        public string? ADDINDEMNITY62 { get; set; }
        public string? MAININTERESTCODE { get; set; }
        public string? MAININTERESTREMARK { get; set; }
        public string? MAINCURRENCY { get; set; }
        public string? MAINSUMINSURED { get; set; }
        public string? ADDINTERESTCODE1 { get; set; }
        public string? ADDINTERESTREMARK1 { get; set; }
        public string? ADDCURRENCY1 { get; set; }
        public string? ADDSUMINSURED1 { get; set; }
        public string? ADDINTERESTCODE2 { get; set; }
        public string? ADDINTERESTREMARK2 { get; set; }
        public string? ADDCURRENCY2 { get; set; }
        public string? ADDSUMINSURED2 { get; set; }
        public string? ADDINTERESTCODE3 { get; set; }
        public string? ADDINTERESTREMARK3 { get; set; }
        public string? ADDCURRENCY3 { get; set; }
        public string? ADDSUMINSURED3 { get; set; }
        public string? ADDINTERESTCODE4 { get; set; }
        public string? ADDINTERESTREMARK4 { get; set; }
        public string? ADDCURRENCY4 { get; set; }
        public string? ADDSUMINSURED4 { get; set; }
        public string? ADDINTERESTCODE5 { get; set; }
        public string? ADDINTERESTREMARK5 { get; set; }
        public string? ADDCURRENCY5 { get; set; }
        public string? ADDSUMINSURED5 { get; set; }
        public string? DCODE1 { get; set; }
        public string? REMARKS1 { get; set; }
        public string? PCTTSI1 { get; set; }
        public string? PCTCL1 { get; set; }
        public string? FIXEDMIN1 { get; set; }
        public string? FIXEDMAX1 { get; set; }
        public string? CURRENCY1 { get; set; }
        public string? DCODE2 { get; set; }
        public string? REMARKS2 { get; set; }
        public string? PCTTSI2 { get; set; }
        public string? PCTCL2 { get; set; }
        public string? FIXEDMIN2 { get; set; }
        public string? FIXEDMAX2 { get; set; }
        public string? CURRENCY2 { get; set; }
        public string? DCODE3 { get; set; }
        public string? REMARKS3 { get; set; }
        public string? PCTTSI3 { get; set; }
        public string? PCTCL3 { get; set; }
        public string? FIXEDMIN3 { get; set; }
        public string? FIXEDMAX3 { get; set; }
        public string? CURRENCY3 { get; set; }
        public string? FEE_ID { get; set; }
        public string? FEE_REMARK { get; set; }
        public string? FEE_CURRENCY { get; set; }
        public string? FEE_AMOUNT { get; set; }
        public string? DUTY_ID { get; set; }
        public string? DUTY_REMARK { get; set; }
        public string? DUTY_CURRENCY { get; set; }
        public string? DUTY_AMOUNT { get; set; }
        public string? BSID1 { get; set; }
        public string? BSFee1 { get; set; }
        public string? BSType1 { get; set; }
        public string? PayorID { get; set; }
        public string? DISCOUNT { get; set; }
        public string? InforceF { get; set; }
        public string? IMMEDIATEINFORCEF { get; set; }
        public string? INSURANCE_TYPE { get; set; }
        public string? LEADERID { get; set; }
        public string? LEADERSHARE { get; set; }
        public string? LEADERFEE { get; set; }
        public string? MEMBERID1 { get; set; }
        public string? MEMBERSHARE1 { get; set; }
        public string? MEMBERCOMM1 { get; set; }
        public string? MEMBERHF1 { get; set; }
        public string? MEMBERPCOLLECTIONF1 { get; set; }
        public string? MEMBERCCOLLECTIONF1 { get; set; }
        public string? MEMBERID2 { get; set; }
        public string? MEMBERSHARE2 { get; set; }
        public string? MEMBERCOMM2 { get; set; }
        public string? MEMBERHF2 { get; set; }
        public string? MEMBERPCOLLECTIONF2 { get; set; }
        public string? MEMBERCCOLLECTIONF2 { get; set; }
        public string? MEMBERID3 { get; set; }
        public string? MEMBERSHARE3 { get; set; }
        public string? MEMBERCOMM3 { get; set; }
        public string? MEMBERHF3 { get; set; }
        public string? MEMBERPCOLLECTIONF3 { get; set; }
        public string? MEMBERCCOLLECTIONF3 { get; set; }
        public string? DCODE4 { get; set; }
        public string? REMARKS4 { get; set; }
        public string? PCTTSI4 { get; set; }
        public string? PCTCL4 { get; set; }
        public string? FIXEDMIN4 { get; set; }
        public string? FIXEDMAX4 { get; set; }
        public string? CURRENCY4 { get; set; }
        public string? DCODE5 { get; set; }
        public string? REMARKS5 { get; set; }
        public string? PCTTSI5 { get; set; }
        public string? PCTCL5 { get; set; }
        public string? FIXEDMIN5 { get; set; }
        public string? FIXEDMAX5 { get; set; }
        public string? CURRENCY5 { get; set; }
        public string? CLAUSE1 { get; set; }
        public string? CLAUSE2 { get; set; }
        public string? CLAUSE3 { get; set; }
        public string? CLAUSE4 { get; set; }
        public string? CLAUSE5 { get; set; }
        public string? CLAUSE6 { get; set; }
        public string? CLAUSE7 { get; set; }
        public string? CLAUSE8 { get; set; }
        public string? CLAUSE9 { get; set; }
        public string? CLAUSE10 { get; set; }
        public string? CLAUSE11 { get; set; }
        public string? CLAUSE12 { get; set; }
        public string? CLAUSE13 { get; set; }
        public string? CLAUSE14 { get; set; }
        public string? CLAUSE15 { get; set; }
    }
}
